SRCS_DIR = ../S

CC = g++
CFLAGS = -O -Wall -Wextra
SRCS = main.cpp
OBJ = main.o Balls.o Celestial.o Interface.o MovementEngine.o olcPixelGameEngine.o
DEPS = Balls.h Celestial.h Interface.h MovementEngine.h oclPixelGameEngine.h VectorOp.h

main = $(OBJ)
	$(CC) -o $@ $< $(CFLAGS)

*.o: %.cpp
	$(CC) -c -o $@ $< $(CFLAGS)

clean:
	rm -f main *.o

.PHONY: clean